version: "3.5"

services:

    domain-nginx:
        build:
            context: ./docker/nginx
            dockerfile: nginx.docker
        container_name: domain.nginx
        working_dir: /var/www
        environment:
            VIRTUAL_HOST: domain.local
            VIRTUAL_PORT: 80
        # environment:
        #     VIRTUAL_HOST: domain.local, dev.domain.local
        #     VIRTUAL_PORT: 443
        #     CERT_NAME: domain.local
        #     LETSENCRYPT_HOST: domain.local
        volumes:
            - ./root:/var/www

    domain-php-fpm72:
        build:
            context: ./docker/php
            dockerfile: php7.2.docker
        container_name: domain.php.fpm72
        working_dir: /var/www
        extra_hosts:
            - "domain.local:${HOST_IP}"
        volumes:
            - ./root:/var/www

    domain-mysql:
        build:
            context: ./docker/mysql
            dockerfile: mysql.docker
        container_name: domain.mysql
        environment:
            - MYSQL_DATABASE=bx_domain_local
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=mysql
        volumes:
            - ./docker/db:/var/lib/mysql

networks:
    default:
        external:
            name: webproxy